### ISSUE TITLE
have a mirror available for blocklist in case ente.dev goes down

### ISSUE THREAD

**Issue by QWIILXEY** [WilliDieEnte/BetterBlocklist#10]
this is just a suggestion but could it be possible for you to host your list on another website (like gitlab as a example) as a mirror in case ente.dev goes down.

**Comment by WilliDieEnte** [comment]
Yeah, will do my bad ^^
Am currently working on it and this will follow in the next couple of days, with some other changes.
Thank you for the suggestion!
