### ISSUE TITLE
Blocklist Cleanup

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [WilliDieEnte/BetterBlocklist#13]
[i] Target: https://ente.dev/api/blocklist/advertising
  [✓] Status: Retrieval successful
  [✓] Parsed 600430 exact domains and 0 ABP-style domains (ignored 1 non-domain entries)
      Sample of non-domain entries:
        - "spryptvqguhpwt"

[i] Target: https://ente.dev/api/blocklist/suspicious
  [✓] Status: Retrieval successful
  [✓] Parsed 805102 exact domains and 0 ABP-style domains (ignored 8 non-domain entries)
      Sample of non-domain entries:
        - "113.116.89.1"
        - "172.88.199.9"
        - "182.116.104.6"
        - "190.238.183.5"
        - "194.226.139.7"

[i] Target: https://ente.dev/api/blocklist/tracking
  [✓] Status: Retrieval successful
  [✓] Parsed 171314 exact domains and 0 ABP-style domains (ignored 1 non-domain entries)
      Sample of non-domain entries:
        - "wpad"

[i] Target: https://ente.dev/api/blocklist/youtube-advertising
  [✓] Status: Retrieval successful
  [✓] Parsed 114482 exact domains and 0 ABP-style domains (ignored 1 non-domain entries)
      Sample of non-domain entries:
        - "head"

**Comment by WilliDieEnte** [comment]
More to it than I thought, see #12 
Also, apologies for taking ages, responses will be faster Soon™️
