### ISSUE TITLE
Can't access the blocklists

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [WilliDieEnte/BetterBlocklist#14]
![brave_xwxUY6A8H5](https://github.com/WilliDieEnte/BetterBlocklist/assets/163652912/7d3a282e-84fc-4274-add5-de168dcfc5d4)

**Comment by WilliDieEnte** [comment]
Heya, thanks for reporting, have implemented a load balancer and service was down for a little while during it, all should have already been fixed long ago, my status page was also annoying me ^-^
