### ISSUE TITLE
FALSE - gateway.icloud.com

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [WilliDieEnte/BetterBlocklist#15]
**Affected Domain(s)**
gateway.icloud.com

**From Blocklist**
Suspicious

**Additional context**
icloud

**Comment by AyanokojiK1yotaka** [comment]
@WilliDieEnte

**Comment by WilliDieEnte** [comment]
Not a false, that is indeed correct. `gateway.icloud.com` is being used by Apple devices to circumvent local DNS resolving and use their service, which isn't wanted by anyone running their own DNS resolver or blocklist, as it would make it useless for certain Apple applications.
(+ the usage for telemetry on the domain as well, which is just yikes, very apple move to use it for multiple purposes to make it harder for everybody...)
I've never been fond of Apple, but that is just down right shady in my personal opinion.
