### ISSUE TITLE
Block these domains

### ISSUE THREAD

**Issue by suricloud** [WilliDieEnte/BetterBlocklist#16]
**Describe your Suggestion**
A detailed description of your Suggestion.
Example: Adding example.com to the Suspicious Blocklist.
Please add these to the ads list:

ads-api.tiktok.com
ads-sg.tiktok.com
business-api.tiktok.com
adtech.yahooinc.com
https://widgets.pinterest.com
https://advertising.yandex.ru

**Describe why you think that would be useful**
A clear and concise description of why you think your Suggestion would benefit everyone.
Example: The Site hosts Malicious content which includes Discord Token Grabbers.

**Describe alternatives you've considered or examples of similar Solutions**
Are there any alternative solutions that already fulfill your Suggestion in a similar form, so that we can use it as our Baseline?

**Additional context**
Add any other context or screenshots about your Suggestion here.

**Comment by WilliDieEnte** [comment]
I'm not so sure if these belong in the suspicious category and not rather into advertising, but accepted nonetheless.
Thank you for your contribution!
