### ISSUE TITLE
SUGGESTION - Blocklist Cleanup

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [WilliDieEnte/BetterBlocklist#18]
[i] Target: https://ente.dev/api/blocklist/advertising
  [✓] Status: No changes detected
  [✓] Parsed 0 exact domains and 0 ABP-style domains (ignored 14 non-domain entries)
      Sample of non-domain entries:
        - "<"
        - "<html>"
        - "<body>"
        - "value="5002">"
        - "value="5555">"

  [i] Target: https://ente.dev/api/blocklist/google-amp
  [✓] Status: No changes detected
  [✓] Parsed 0 exact domains and 0 ABP-style domains (ignored 14 non-domain entries)
      Sample of non-domain entries:
        - "<"
        - "<html>"
        - "<body>"
        - "value="5002">"
        - "value="5555">"

  [i] Target: https://ente.dev/api/blocklist/suspicious
  [✓] Status: No changes detected
  [✓] Parsed 0 exact domains and 0 ABP-style domains (ignored 14 non-domain entries)
      Sample of non-domain entries:
        - "<"
        - "<html>"
        - "<body>"
        - "value="5002">"
        - "value="5555">"

  [i] Target: https://ente.dev/api/blocklist/tracking
  [✓] Status: No changes detected
  [✓] Parsed 0 exact domains and 0 ABP-style domains (ignored 14 non-domain entries)
      Sample of non-domain entries:
        - "<"
        - "<html>"
        - "<body>"
        - "value="5002">"
        - "value="5555">"

  [i] Target: https://ente.dev/api/blocklist/tv
  [✓] Status: No changes detected
  [✓] Parsed 0 exact domains and 0 ABP-style domains (ignored 14 non-domain entries)
      Sample of non-domain entries:
        - "<"
        - "<html>"
        - "<body>"
        - "value="5002">"
        - "value="5555">"

  [i] Target: https://ente.dev/api/blocklist/youtube-advertising
  [✓] Status: No changes detected
  [✓] Parsed 0 exact domains and 0 ABP-style domains (ignored 14 non-domain entries)
      Sample of non-domain entries:
        - "<"
        - "<html>"
        - "<body>"
        - "value="5002">"
        - "value="5555">"

**Comment by WilliDieEnte** [comment]
same applies as in #13 >~<
