### ISSUE TITLE
skyblockmods.com

### ISSUE THREAD

**Issue by UnknownRebell** [WilliDieEnte/BetterBlocklist#2]
Add "skyblockmods.com" to the Suspicious Blocklist.

 The Site hosts Malicious content which includes Minecraft Token Grabbers.

This side usually spreads on hypixel skyblock by bots. if you install this mod, your account will be used to spread the mod.

**Comment by WilliDieEnte** [comment]
Thanks for the Report, I've added it to the Suspicious list :3
