### ISSUE TITLE
FALSE - ocfconnect-shard-eu02-euwest1.samsungiotcloud.com

### ISSUE THREAD

**Issue by sefinek** [WilliDieEnte/BetterBlocklist#20]
**Affected Domain(s)**
ocfconnect-shard-eu02-euwest1.samsungiotcloud.com

**From Blocklist**
https://ente.dev/api/blocklist/tv

**Additional context**
Blocking this subdomain prevents a Samsung refrigerator from being added to the `SmartThings` app.

**Comment by WilliDieEnte** [comment]
Also added, thanks again :3

**Comment by WilliDieEnte** [comment]
Confused issue IDs ignore this back and forth...
I sadly couldn't verify this one in contrary to #21

**Comment by sefinek** [comment]
I see that the subdomain `ocfconnect-shard-eu02-euwest1.samsungiotcloud.com` has already disappeared from your lists

Thanks

**Comment by WilliDieEnte** [comment]
yep, I'm currently working on it a lot, especially with such specific lists; I'd rather miss one than block one too many...
