### ISSUE TITLE
FALSE - eu-auth2.samsungosp.com

### ISSUE THREAD

**Issue by sefinek** [WilliDieEnte/BetterBlocklist#21]
**Affected Domain(s)**
eu-auth2.samsungosp.com

**From Blocklist**
https://ente.dev/api/blocklist/tv

**Additional context**
Blocking this subdomain prevents a Samsung refrigerator from being added to the `SmartThings` app.

**Comment by WilliDieEnte** [comment]
Added! Thank you very much for the contribution ^-^

**Comment by WilliDieEnte** [comment]
That's unfortunate, I haven't encountered a smart fridge in the wild yet - whitelisted it, thank you for reporting, and I'll keep an eye out ^^

**Comment by sefinek** [comment]
AI is almost everywhere now (:
