### ISSUE TITLE
ad scam thingy

### ISSUE THREAD

**Issue by UnknownRebell** [WilliDieEnte/BetterBlocklist#3]
Adding stmxal.breadneighbourwave.top to the Suspicious Blocklist.

Its one of these "YOU WON X$ AMAZON CARD GIMME YOUR DATA TO RECEIVE IT" sites

the full link: (it was to long so i uploadet it to GB .-.) 
https://ghostbin.com/ro3Tx

**Comment by WilliDieEnte** [comment]
Thanks for your Report, it's now also included and blocked in the future :D
