### ISSUE TITLE
FALSE - brightcove.map.fastly.net

### ISSUE THREAD

**Issue by Knuschberkeks** [WilliDieEnte/BetterBlocklist#4]
**From Blocklist**
tracking

**Additional context**
The official Formula 1 App on iOS uses this domain to provide video content.

**Comment by WilliDieEnte** [comment]
Heya, sorry for your long waiting time, I just totally forgot about it xd
Fixed it with your other Issue #5 and some others I've come across while testing 👍 

Thanks for the report and have a nice day!
