### ISSUE TITLE
FALSE - shalom.it

### ISSUE THREAD

**Issue by mariomare22** [WilliDieEnte/BetterBlocklist#7]
**Affected Domain(s)**
shalom.it

**From Blocklist**
Suspicious

**Additional context**
Currently, the site no longer shows a phishing page.
The site has probably been phishing-free for at least four years: https://urlscan.io/search/#shalom.it

Thanks

**Comment by WilliDieEnte** [comment]
My bad for not answering way faster 👀
Has already been fixed since January 👍 

Wish you a nice day :)
